### Natural language
- Every operation is dealing with language
- To get access of the language we need one library(NLTK)
- Tokenization
- stop words removal
- 

### Tokenization

In [1]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.


True

In [2]:
# Tokenization- Word,sentence

from nltk.tokenize import word_tokenize,sent_tokenize

In [3]:
text="I have bought several of the Vitality canned dog food products and have found them all to be of good quality. The product looks more like a stew than a processed meat and it smells better. My Labrador is finicky and she appreciates this product better than  most."


In [4]:
words=word_tokenize(text)
words

['I',
 'have',
 'bought',
 'several',
 'of',
 'the',
 'Vitality',
 'canned',
 'dog',
 'food',
 'products',
 'and',
 'have',
 'found',
 'them',
 'all',
 'to',
 'be',
 'of',
 'good',
 'quality',
 '.',
 'The',
 'product',
 'looks',
 'more',
 'like',
 'a',
 'stew',
 'than',
 'a',
 'processed',
 'meat',
 'and',
 'it',
 'smells',
 'better',
 '.',
 'My',
 'Labrador',
 'is',
 'finicky',
 'and',
 'she',
 'appreciates',
 'this',
 'product',
 'better',
 'than',
 'most',
 '.']

In [5]:
sent=sent_tokenize(text)
sent

['I have bought several of the Vitality canned dog food products and have found them all to be of good quality.',
 'The product looks more like a stew than a processed meat and it smells better.',
 'My Labrador is finicky and she appreciates this product better than  most.']

### stopwords

In [6]:
from nltk.corpus import stopwords

In [7]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

In [12]:
stop=set(stopwords.words('english'))
filtered_words=[word for word in words if word.lower() not in stop]
print(filtered_words)

['bought', 'several', 'Vitality', 'canned', 'dog', 'food', 'products', 'found', 'good', 'quality', '.', 'product', 'looks', 'like', 'stew', 'processed', 'meat', 'smells', 'better', '.', 'Labrador', 'finicky', 'appreciates', 'product', 'better', '.']


### POS-Tagging

In [13]:
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping taggers\averaged_perceptron_tagger.zip.


True

In [14]:
pos_tags=nltk.pos_tag(words)
pos_tags

[('I', 'PRP'),
 ('have', 'VBP'),
 ('bought', 'VBN'),
 ('several', 'JJ'),
 ('of', 'IN'),
 ('the', 'DT'),
 ('Vitality', 'NNP'),
 ('canned', 'VBD'),
 ('dog', 'RP'),
 ('food', 'NN'),
 ('products', 'NNS'),
 ('and', 'CC'),
 ('have', 'VBP'),
 ('found', 'VBN'),
 ('them', 'PRP'),
 ('all', 'DT'),
 ('to', 'TO'),
 ('be', 'VB'),
 ('of', 'IN'),
 ('good', 'JJ'),
 ('quality', 'NN'),
 ('.', '.'),
 ('The', 'DT'),
 ('product', 'NN'),
 ('looks', 'VBZ'),
 ('more', 'RBR'),
 ('like', 'IN'),
 ('a', 'DT'),
 ('stew', 'NN'),
 ('than', 'IN'),
 ('a', 'DT'),
 ('processed', 'JJ'),
 ('meat', 'NN'),
 ('and', 'CC'),
 ('it', 'PRP'),
 ('smells', 'VBZ'),
 ('better', 'RBR'),
 ('.', '.'),
 ('My', 'PRP$'),
 ('Labrador', 'NNP'),
 ('is', 'VBZ'),
 ('finicky', 'JJ'),
 ('and', 'CC'),
 ('she', 'PRP'),
 ('appreciates', 'VBZ'),
 ('this', 'DT'),
 ('product', 'NN'),
 ('better', 'JJR'),
 ('than', 'IN'),
 ('most', 'JJS'),
 ('.', '.')]

### Lemmatization and Stemming

In [15]:
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...


True

In [19]:
nltk.download('omw-1.4')

[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...


True

In [20]:
lemmatizer=WordNetLemmatizer()

In [21]:
lemmatized_words=[lemmatizer.lemmatize(word) for word in words]
print(lemmatized_words)

['I', 'have', 'bought', 'several', 'of', 'the', 'Vitality', 'canned', 'dog', 'food', 'product', 'and', 'have', 'found', 'them', 'all', 'to', 'be', 'of', 'good', 'quality', '.', 'The', 'product', 'look', 'more', 'like', 'a', 'stew', 'than', 'a', 'processed', 'meat', 'and', 'it', 'smell', 'better', '.', 'My', 'Labrador', 'is', 'finicky', 'and', 'she', 'appreciates', 'this', 'product', 'better', 'than', 'most', '.']


### Named Entity Recognition

In [22]:
# to use NSE we need too 
nltk.download('maxent_ne_chunker')

[nltk_data] Downloading package maxent_ne_chunker to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping chunkers\maxent_ne_chunker.zip.


True

In [24]:
nltk.download('words')

[nltk_data] Downloading package words to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\words.zip.


True

In [25]:
ner_tags=nltk.ne_chunk(pos_tags)

In [26]:
print(ner_tags)

(S
  I/PRP
  have/VBP
  bought/VBN
  several/JJ
  of/IN
  the/DT
  (ORGANIZATION Vitality/NNP)
  canned/VBD
  dog/RP
  food/NN
  products/NNS
  and/CC
  have/VBP
  found/VBN
  them/PRP
  all/DT
  to/TO
  be/VB
  of/IN
  good/JJ
  quality/NN
  ./.
  The/DT
  product/NN
  looks/VBZ
  more/RBR
  like/IN
  a/DT
  stew/NN
  than/IN
  a/DT
  processed/JJ
  meat/NN
  and/CC
  it/PRP
  smells/VBZ
  better/RBR
  ./.
  My/PRP$
  (ORGANIZATION Labrador/NNP)
  is/VBZ
  finicky/JJ
  and/CC
  she/PRP
  appreciates/VBZ
  this/DT
  product/NN
  better/JJR
  than/IN
  most/JJS
  ./.)


### Sentiment Analysis

In [27]:
from nltk.sentiment import SentimentIntensityAnalyzer


In [28]:
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...


True

In [30]:
sentiment_analyser=SentimentIntensityAnalyzer()


In [31]:
text1="NLTK is awesome"

In [33]:
sentiment_score=sentiment_analyser.polarity_scores(text1)
print(sentiment_score)

{'neg': 0.0, 'neu': 0.328, 'pos': 0.672, 'compound': 0.6249}


### Vectorization
- bag of words
- TF-IDF
- Word Embedding


In [34]:
# bag of words
from sklearn.feature_extraction.text import CountVectorizer

In [35]:
corpus=[
    " I love natural language processing ",
    " Machine learning is fascinating",
    " I enjoy working with python"
]

In [36]:
vectorizer=CountVectorizer()

In [37]:
X=vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names_out())# get the feature name(worsds)
print(X.toarray())#convert the sparce matrix to a dense array representaion

['enjoy' 'fascinating' 'is' 'language' 'learning' 'love' 'machine'
 'natural' 'processing' 'python' 'with' 'working']
[[0 0 0 1 0 1 0 1 1 0 0 0]
 [0 1 1 0 1 0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 1 1 1]]


### TF-IDF

In [38]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [39]:
corpus=[
    " I love natural language processing ",
    " Machine learning is fascinating",
    " I enjoy working with python"
]

In [40]:
vectorizer=TfidfVectorizer()

In [41]:
X=vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names_out())# get the feature name(worsds)
print(X.toarray())#convert the sparce matrix to a dense array representaion

['enjoy' 'fascinating' 'is' 'language' 'learning' 'love' 'machine'
 'natural' 'processing' 'python' 'with' 'working']
[[0.  0.  0.  0.5 0.  0.5 0.  0.5 0.5 0.  0.  0. ]
 [0.  0.5 0.5 0.  0.5 0.  0.5 0.  0.  0.  0.  0. ]
 [0.5 0.  0.  0.  0.  0.  0.  0.  0.  0.5 0.5 0.5]]


### Word Embedding

In [42]:
import numpy as np


In [43]:
word_embedding={
    'love': np.array([0.2,0.4,-0.5]),
    'natural': np.array([0.1,0.2,0.3]),
    'language':np.array([0.6,-0.2,0.3]),
    'processing':np.array([-0.3,0.7,0.4])
}

In [47]:
doc="love natural language processing"
words=doc.lower().split()
doc_embedding=np.mean([word_embedding[word] for word in words],axis=0)

In [48]:
print(doc_embedding)

[0.15  0.275 0.125]
